sspi_flask_app/api/core/collect.py

I added a collect route, tested it, and everything works! Yay!

Financial depth

---

sspi_flask_app/api/core/collect.py
sspi_flask_app/api/core/compute.py
sspi_flask_app/api/datasource/oecdstat.py
sspi_flask_app/api/datasource/sdg.py
sspi_flask_app/models/database.py

enumerate is your best friend... until its not. Close #194

Fixed issue with collect routes

---

documentation.md
sspi_flask_app/__init__.py
sspi_flask_app/api/core/compute.py
sspi_flask_app/api/datasource/sdg.py
sspi_flask_app/api/resources/utilities.py
sspi_flask_app/models/database.py
sspi_flask_app/models/errors.py
tests/unit/compute/test_zip_intermediates.py
tests/unit/models/test_mongo_wrapper.py

Updated again. Units are working for intermediaries (sorta hard coded), but not for the overall country, year observation. Wrote more generalized utility function for intermediary aggregation, and wrote some documentation.

Merging changes to watman

---

sspi_flask_app/__init__.py
sspi_flask_app/api/core/dashboard.py
sspi_flask_app/api/core/finalize.py
sspi_flask_app/api/resources/utilities.py
sspi_flask_app/auth/routes.py
sspi_flask_app/client/routes.py
sspi_flask_app/client/static/charts/dataMatrix.js
sspi_flask_app/client/static/css/data-overview.css
sspi_flask_app/client/templates/country-comparisons/sweden-france-japan.html
sspi_flask_app/client/templates/data-overview.html
sspi_flask_app/client/templates/indicator-data.html
sspi_flask_app/models/database.py

- **style: Whitespace adjustments**
- **feat: Wrote CountryGroup Getter**
- **feat: Initialized MVC for Data Overview Page**
- **style: Whitespace Adjustment**
- **feat: Setting Up Preprocessing for Finished Data**
- **fix: Adjusting Imports and Templates**
- **feat: Structured Final JSON Data**
- **feat: Grouped Matrix Data by Country and Year**
- **fix: Updated Database Lookup**
- **fix: Minor Updates to HTML files**
- **feat: Structured Data Matrix Visualization**

Set Up State of Data Page

---

local/indicator-problems.json
sspi_flask_app/api/core/finalize.py
sspi_flask_app/client/static/charts/data-matrix-dynamic.js
sspi_flask_app/client/static/css/data-overview.css
sspi_flask_app/client/templates/data-overview.html

- **feat: Accounted for Route Status in Data Matrix**
- **feat: Implemented Indicator Problems Local File for Status**
- **feat: Style Updates for Data Matrix Frontend**
- **fix: Style Updates to Match Colors**

Implemented Better Data Overview Page

---

sspi_flask_app/api/core/collect.py
sspi_flask_app/api/datasource/epi.py
sspi_flask_app/api/datasource/sdg.py

This is an important bit of code to review @maxstrr. Anything we collect from 
the internet (which is to say, everything) can be written as a collect route
Closes #40
- **style: Adjusted Whitespace**
- **style: Adjusted Whitespace**
- **feat: Wr**

Implemented Collect Route for NITROG

---

sspi_flask_app/api/core/collect.py
sspi_flask_app/api/core/compute.py
sspi_flask_app/api/datasource/epi.py

NITROG Compute reads the virtual CSV file made from the original string pulled
out of the database. Note that **collect should do as little as possible to the
original data**; it is compute's job to process.
See also #282 (Implemented Collect Route for NITROG)
Closes #126, #9
- **style: Adjusted Whitespace**
- **style: Adjusted Whitespace**
- **feat: Wr**
- **style: Whitespace in imports**
- **feat: Revised and Completed Collect and Compute Routes for NITROG**

Implemented Compute for NITROG

---

tests/integration/test_sspi_score_real_data.py
tests/unit/adapters/test_raw_insert_one.py
tests/unit/compute/test_zip_intermediates.py
tests/unit/models/test_mongo_wrapper.py
tests/unit/models/test_sspi_characterstics_database.py
tests/unit/models/test_sspi_score.py

refactor: Adjusted imports in testing

---

sspi_flask_app/api/core/finalize.py
sspi_flask_app/api/resources/utilities.py
sspi_flask_app/client/static/charts/category-radar-static.js
sspi_flask_app/models/database/__init__.py
sspi_flask_app/models/database/mongo_wrapper.py

Closes #296, #297
- **fix: Added sspi_static_rank_data Collection**
- **feat: Implemented Ranking Computation Routes**
- **fix: Adjusted Database Lookup Functions**
- **fix: Adjusted Find One to Allow for Option Passing**
- **refactor: Adjusted Category Static Radar to Export Chart Class**
- **feat: Rankings Show on Highlight**

Compute, Store, and Show Ranks for Static Data

---

sspi_flask_app/client/static/charts/score-bar-static.js
sspi_flask_app/client/static/css/score-bar.css
sspi_flask_app/client/templates/scores.html

fix: Implemented Wrapping for Pillars in `/scores`

---

sspi_flask_app/client/static/charts/score-bar-static.js
sspi_flask_app/client/templates/scores.html

feat: Highlights Propagate Across Charts

---

sspi_flask_app/client/templates/indicator-data.html

fix: Changed Indicator Static Chart to Score Bar Static

---

local/IndicatorDetails.csv
sspi_flask_app/client/templates/indicator-options.html

Closes #327
- **fix: Adjusted IndicatorDetails.csv for Correct Order**
- **fix: Fixed Indicator Order in Options**

327 fix category titles in sspi metadata

---

sspi_flask_app/__init__.py
sspi_flask_app/api/core/bulk.py
sspi_flask_app/api/datasource/wid.py
sspi_flask_app/models/database/__init__.py
sspi_flask_app/models/database/mongo_wrapper.py
sspi_flask_app/models/database/sspi_bulk_data.py
sspi_flask_app/models/database/sspi_main_data_v3.py

Implements Bulk Data Downloading from a Download Link.
- **feat: Implemented Bulk Database with Validators**
- **feat: Initialized and Registered Bulk Blueprint**
- **feat: Implemented Bulk Collect for WID**
- **feat: Wrote Bulk Collect Storage Schema for WID**
- **fix: Implemented Fragmenting for sspi_bulk_data**

Bulk Data Download for WID

---

sspi_flask_app/client/templates/paper-resources.html

- **feat: Implemented Functional Save Buttons**
- **feat: Moved Save Buttons Outside the Canvas**
- **feat: Saved with Transparent Background**

363 savable radar chart images

---

sspi_flask_app/client/static/charts/score-bar-static.js
sspi_flask_app/client/static/css/score-bar.css
sspi_flask_app/client/static/js/capture-chart.js
sspi_flask_app/client/static/script.js
sspi_flask_app/client/templates/category-data.html
sspi_flask_app/client/templates/category-options.html
sspi_flask_app/client/templates/indicator-data.html
sspi_flask_app/client/templates/indicator-options.html
sspi_flask_app/client/templates/layout.html
sspi_flask_app/client/templates/paper-resources.html

- **fix: Updated Codes and Titles for Dropdown Options**
- **feat: Implemented Summary Stats Below Charts**
- **feat: Roughed Out a Chart Capture Utility**

377 static bar summary statistics

---

sspi_flask_app/models/database/__init__.py

- **feat: Setup sspi_outcome_data Database**
- **feat: Adjusted to Create Separate Raw and Clean Databases**
- **fix: Adjusted imports**

386 create outcome variable database

---

sspi_flask_app/api/core/collect.py
sspi_flask_app/api/resources/utilities.py

- **feat: Wrote GDPMEK Collect Route**
- **feat: Implemented Basic Structure of /GDPMER Route**
- **feat: Implemented /collect/GDPMER**
- **fix: Added new outcome databases to lookup**
- **feat: Implemented /collect/GDPPPP**

385 collect gdppercapita mer data

---

requirements.txt

- **feat: Setup sspi_outcome_data Database**
- **feat: Adjusted to Create Separate Raw and Clean Databases**
- **fix: Adjusted imports**
- **fix: Added Dependency for openpyxl**

388 add openpyxl dependency in requirementstxt

---

sspi_flask_app/api/core/collect.py
sspi_flask_app/api/datasource/oecdstat.py

- **feat: Implemented Datasource Utility for OECDSDMX**
- **feat: Implemented /api/v1/collect/FORAID**

93 implement collectforaid

---

scripts/json_diff.py
sspi_flask_app/api/core/dashboard.py
sspi_flask_app/api/core/finalize.py
sspi_flask_app/client/static/charts/indicator-line-dynamic.js
sspi_flask_app/client/templates/indicator-data.html

- **feat: Implemented Download Functions for Indicator Dynamic Line Data**
- **feat: Implemented Symmetric Difference Utility for JSON Comparisons**
- **feat: Revised Year Ranges and Filled null for Missing Years**
- **feat: Implemented Dashing for Gap Fill**

418 mismatching years on indicator dynamic line

---

local/indicator-problems.json
sspi_flask_app/api/core/collect.py
sspi_flask_app/api/datasource/fao.py

- **feat: Implemented /api/v1/collect/CARBON**
- **fix: Updated Indicator Problems Acccounting in JSON**

44 implement collectcarbon

---

sspi_flask_app/api/core/compute/SUS/compute_lnd.py
sspi_flask_app/api/resources/utilities.py

- **fix: Fixed an error in zip_intermediates for zero scores being omitted**
- **feat: Implemented /api/v1/compute/DEFRST**

129 implement computedefrst

---

sspi_flask_app/api/core/collect.py
sspi_flask_app/api/core/compute/SUS/compute_lnd.py

- **fix: Adjusted /api/v1/collect/CARBON element code**
- **feat: Implemented /api/v1/compute/CARBON**

130 implement computecarbon

---

sspi_flask_app/api/core/collect.py
sspi_flask_app/api/core/compute/PG/compute_edu.py

- **style: Whitespace**
- **finished puptch**
- **finalized pupil to teacher ratio**

169 implement computepuptch

---

sspi_flask_app/api/core/collect.py
sspi_flask_app/api/core/compute/PG/compute_inf.py
sspi_flask_app/api/core/compute/PG/compute_saf.py
sspi_flask_app/api/datasource/fsi.py
sspi_flask_app/api/resources/utilities.py

I included some of the cleaning work here by accident sorry
- **wrote part of fsi collect, and got all excel file links**
- **secapp mostly cleaned**

Implemented SECAPP collect

---

README.md
scripts/setup

- **feat: Implemented Setup Script to Automate Chores**
- **docs: Documented New Setup Script**

468 implement basic setup script to handle the basics in bash

---

sspi_flask_app/auth/routes.py
sspi_flask_app/models/database/sspi_raw_api_data.py

- **fix: Checked that next is not None**
- **fix: sspi_raw_api_data treats and expects datetimes as strings**

471 fix collectedat logic for push

---

issues
local/indicator-confident.json
local/indicator-problems.json
sspi_flask_app/api/core/compute/MS/compute_neq.py

- **feat: Implemented /api/v1/compute/GINIPT**
- **content: Updated indicator status files**

165 implement computeginipt

---

sspi_flask_app/api/core/compute/PG/compute_rts.py
sspi_flask_app/api/datasource/vdem.py

- **feat: Implemented Use of Auto-fragmentation for RULELW and EDEMOC**
- **fix: Removed Unused Imports**

505 integrate with automatic fragmentation

---

connector/SSPIDatabaseConnector.py
sspi_flask_app/api/core/collect.py
sspi_flask_app/api/core/compute/SUS/compute_ghg.py
sspi_flask_app/api/core/sync.py
sspi_flask_app/api/datasource/fao.py

- **style: Regrouped BEEFMK outside of land**
- **feat: Implemented Filtering for /api/v1/compute/BEEMK; reduced /api/v1/collect/BEEFMK**
- **fix: Removed Misplaced Comma in Database Connector**
- **fix: Adapted Sync Routes to Handle Messages Instead of Response Objects**
- **feat: Implemented /api/v1/compute/BEEFMK**

Compute BEEFMK

---

sspi_flask_app/api/resources/utilities.py
sspi_flask_app/models/database/mongo_wrapper.py
tests/unit/compute/test_zip_intermediates.py

- **feat: Implemented ItemCode and Items List Support in zip_intermediates**
- **test: Implemented Tests for the Handling of Items**

528 update zip intermediates to handle the creation of extrasitemsanalysis lists

---

sspi_flask_app/api/core/collect.py
sspi_flask_app/api/core/compute/MS/compute_wwb.py
sspi_flask_app/models/database/mongo_wrapper.py

- **fix: Updated /api/v1/collect/SENIOR to use New OECD Collect Utility**
- **feat: Implemented Filtering and Preprocessing for /api/v1/compute/SENIOR**
- **feat: Implemented Item List Validation**
- **feat: Completed Data Cleaning for /api/v1/compute/SENIOR**
Did not complete the indicator: imputations to linearly interpolate between years of data is required before `zip_intermediates` is called, which requires decisions on how interpolation and extrapolation globall

Completed Data Cleaning for /api/v1/compute/SENIOR

---

cli/cli.py
cli/utilities.py
connector/SSPIDatabaseConnector.py
scripts/push
sspi_flask_app/api/core/finalize.py
sspi_flask_app/api/core/sync.py

- **feat: Implemented Bulk Push Script**
- **fix: Further Tightened the .call() Method**
- **feat: Implemented Better Messaging**

539 debug push

---

sspi_flask_app/client/static/charts/indicator-line-dynamic.js
sspi_flask_app/client/static/script.js

- **feat: Implemented Backward Extrapolation Lines**
- **feat: Implemented Infrastructure for Backward Extrapolation Toggling**
- **feat: Implemented Extrapolation Checkbox Toggle**

543 implement backward constant extrapolation when data is missing in dynamic line

---

cli/cli.py
cli/utilities.py
sspi_flask_app/api/core/delete.py

- **feat: Implemented Improved Database Clearing Tool**
- **fix: Adjusted Spacing of Confirmation Output**
- **feat: Implemented Working sspi database clear**

484 fix delete forms to work with cli and sspidatabaseconnector

---

config.py
sspi_flask_app/api/core/collect.py
sspi_flask_app/api/core/compute/PG/compute_glb.py
sspi_flask_app/api/core/finalize.py
sspi_flask_app/auth/routes.py
tests/conftest.py
tests/unit/security/__init__.py
tests/unit/security/test_auth_bp.py
tests/unit/security/test_collect_bp.py
tests/unit/security/test_compute_bp.py
tests/unit/security/test_delete_bp.py
tests/unit/security/test_finalize_bp.py
tests/unit/security/test_load_bp.py
tests/unit/security/test_save_bp.py
tests/unit/security/test_sync_bp.py

- **tests: Implemented Route Testing for @login_required Protection By Blueprint**
- **fix: Removed Bad Testing Configuration**
- **fix: Caught several major @login_required omissions**

99 implement testing for authorization and security

---

cli/cli.py
sspi_flask_app/api/core/save.py
sspi_flask_app/logging.py
tests/unit/test_save.py

- **fix: Touched Up the Logic to /api/v1/save**
- **tests: Implemented Basic Sanity Check Tests for save_bp**
- **feat: Implemented CLI Support for Save**

gh run watch

---

cli/cli.py
cli/utilities.py
sspi_flask_app/api/core/compute/MS/compute_fin.py
sspi_flask_app/api/core/compute/MS/compute_neq.py
sspi_flask_app/api/core/compute/MS/compute_wwb.py
sspi_flask_app/api/core/compute/PG/compute_glb.py
sspi_flask_app/api/core/compute/PG/compute_inf.py
sspi_flask_app/api/core/compute/PG/compute_saf.py
sspi_flask_app/api/core/compute/SUS/compute_eco.py
sspi_flask_app/api/core/compute/SUS/compute_ghg.py
sspi_flask_app/api/core/compute/SUS/compute_lnd.py
sspi_flask_app/api/core/compute/SUS/compute_nrg.py
sspi_flask_app/api/core/impute.py
sspi_flask_app/api/datasource/oecdstat.py
sspi_flask_app/api/resources/utilities.py
sspi_flask_app/models/database/__init__.py
sspi_flask_app/models/database/mongo_wrapper.py
sspi_flask_app/models/database/sspi_clean_api_data.py

- **feat: Implemented Support for sspi_incomplete_api_data**
- **feat: Implemented CLI Support For Imputations**

531 implement imputation schema

---

cli/cli.py
cli/commands/extrapolate.py
cli/utilities.py
connector/SSPIDatabaseConnector.py
sspi_flask_app/api/core/dashboard.py
sspi_flask_app/api/core/impute.py
sspi_flask_app/api/resources/utilities.py
sspi_flask_app/client/static/charts/indicator-line-dynamic.js
sspi_flask_app/client/static/script.js
tests/unit/utilities/test_extrapolate_backward.py
tests/unit/utilities/test_extrapolate_backwards.py

- **feat: Implemented Logic for extrapolate_backwards**
- **tests: Implemented Basic Unit Tests for Extrapolate Backwards**

562 implement extrapolate backwards

---

cli/cli.py
cli/commands/panel.py
sspi_flask_app/api/core/dashboard.py
sspi_flask_app/api/resources/utilities.py
sspi_flask_app/client/templates/panel-plot.html
sspi_flask_app/models/database/__init__.py
sspi_flask_app/models/database/mongo_wrapper.py
sspi_flask_app/models/database/sspi_panel_data.py
tests/unit/utilities/test_generate_item_levels.py

- **tests: Implemented Unit Tests for generate_item_levels**
- **feat: Implemented Infrastructure for SSPIPanelData**
- **feat: Implemented sspi panel levels and sspi panel plot**
- **feat: Implemented sspi panel plot Data Processing**
- **feat: Setup Series Identifiers and Length Warning**
- **feat: Implemented /api/v1/view/panel Structure**

568 implement plotting utility for generating line plots

---

cli/cli.py
cli/commands/country.py
sspi_flask_app/api/core/impute.py
sspi_flask_app/api/datasource/sdg.py
sspi_flask_app/api/resources/utilities.py
sspi_flask_app/models/database/mongo_wrapper.py
sspi_flask_app/models/database/sspi_metadata.py

Implemented NRGINT Imputations. Hardly any data to impute: just forward extrapolation to cover 2023 based on 2022's data.
- **feat: Implemented /api/v1/impute/NRGINT**
In the course of doing this, a number of bugs were found and fixed:
- **fix: Validators and SDG Now Correctly Drop NaN Values**
- **fix: Minor Semantic Improvements to Indicator Goalposting Function**
- **fix: find() method Now Defaults To Dropping _id Keys**
- **fix: Typing and Docstring for get_goalposts**
- **fix: SENIOR Dummy Route Returns JSON**
Finally, while examining these errors I had need to lookup countries by code, so I implemented a CLI Utility that wraps pycountry's search_fuzzy feature.
- **feat: Implemented sspi country Utility To Get Country Info Quickly**

593 implement apiv1imputenrgint

---

sspi_flask_app/api/core/impute.py

Quick PR using the boilerplate and utility functions from the last few to mow down an easy indicator.

feat: Implemented /api/v1/impute/YRSEDU

---

datasets/unsdg_basela/documentation.md
datasets/unsdg_minmat/documentation.md
datasets/unsdg_montrl/documentation.md
datasets/unsdg_rotdam/documentation.md
datasets/unsdg_stkhlm/documentation.md
methodology/sus/lnd/chmpol/methodology.md
sspi_flask_app/api/core/datasets/unsdg_basela.py
sspi_flask_app/api/core/datasets/unsdg_minmat.py
sspi_flask_app/api/core/datasets/unsdg_montrl.py
sspi_flask_app/api/core/datasets/unsdg_rotdam.py
sspi_flask_app/api/core/datasets/unsdg_stkhlm.py
sspi_flask_app/api/core/sspi/sus/lnd/chmpol.py

- **documentation: Updated Methodology for CHMPOL Datasets**
- **feat: Implemented Collectors and Cleaners for CHMPOL Datasets**
- **documentation: Notes on Potential Issues**
- **feat: Updated Compute CHMPOL**

545 update apiv1computestkhlm to use intermediates for montreal et al

---

CLAUDE.md
sspi_flask_app/api/core/finalize.py
sspi_flask_app/models/sspi.py
tests/unit/models/test_sspi_score.py

- **documentation: Extra instructions for CLAUDE.md**
- **fix: SSPI Scoring Year Handling is Better**

733 fix scoring bug in sspi class

---

DATASET_STATUS_REPORT.md
datasets/unsdg/unsdg_wtstrs/documentation.md
datasets/unsdg/unsdg_wuseff/documentation.md
methodology/sus/lnd/watman/methodology.md
sspi_flask_app/api/core/datasets/unsdg/unsdg_wtstrs.py
sspi_flask_app/api/core/datasets/unsdg/unsdg_wuseff.py
sspi_flask_app/api/core/sspi/sus/lnd/watman.py

- **fix: Named CWUEFF -> WUSEFF**
- **fix: WATMAN Datasets Now Collect and Clean Correctly**

759 update watman to collect unfao wuseff instead of unfao cwueff

---

datasets/unsdg/unsdg_nrgint/documentation.md
methodology/sus/nrg/nrgint/methodology.md
sspi_flask_app/api/core/datasets/unsdg/unsdg_nrgint.py

- **feat: UNFAO Data Collectors Are Working Again**
- **fix: CARBON compute updated**
- **fix: NRGINT Now Pulls from UNSDG_NRGINT**

764 update nrgint collector

---

datasets/epi/epi_mswgen/documentation.md
methodology/sus/nrg/nrgint/methodology.md
methodology/sus/wst/mswgen/methodology.md
sspi_flask_app/api/core/sspi/sus/eco/biodiv.py
sspi_flask_app/api/core/sspi/sus/wst/mswgen.py

Closes #51 and #136
- **fix: Added Back Required IndicatorCode: NRGINT**
- **feat: Collect, Clean, and Computed MSWGEN Implemented**
- **style: BIODIV**

51 implement collectmswgen 2

---

CLAUDE.md
sspi_flask_app/api/core/sspi/sus/eco/biodiv.py
sspi_flask_app/api/core/sspi/sus/ghg/beefmk.py
sspi_flask_app/api/core/sspi/sus/ghg/coalpw.py
sspi_flask_app/api/core/sspi/sus/lnd/carbon.py
sspi_flask_app/api/core/sspi/sus/lnd/defrst.py
sspi_flask_app/api/core/sspi/sus/lnd/watman.py
sspi_flask_app/api/core/sspi/sus/nrg/airpol.py
sspi_flask_app/api/core/sspi/sus/nrg/altnrg.py
sspi_flask_app/api/core/sspi/sus/wst/recycl.py
sspi_flask_app/api/core/sspi/sus/wst/stcons.py
sspi_flask_app/api/resources/utilities.py
tests/unit/utilities/test_slice_filter_utilities.py

Imputations for Sustainability Indicators
Closes #598
Closes #597
Closes #596
Closes #594
Closes #591
Closes #590
Closes #589
Closes #587
Closes #767
- **fix: BIODIV Placeholder Imputations**
- **fix: Removed Unneeded Print STatement**
- **fix: Imputations for STCONS**
- **fix: Boilerplate for RECYCL**
- **fix: Imputations for ALTNRG**
- **fix: Imputations for AIRPOL**
- **fix: Imputations for WATMAN**
- **fix: Imputations for BEEFMK**
- **fix: Imputations for COALPW**
- **fix: Imputations for CARBON**
- **fix: Imputations for DEFRST**
- **documentation: Behavior of sspi query clean [ITEMCODE]**

768 fill out imputation for sus
